### ISSUE TITLE
Include search box to filter down options

### ISSUE THREAD

**Issue by astrofrog** [astrofrog/acknowledgment-generator#12]
As time goes on, it is likely there will be hundreds of facilities and codes, so it would be a good idea to be able to filter down the number of options with a kind of search box.

**Comment by slowe** [comment]
I've had a go at concatenating anything containing "made use of". The results look like this...
Before ![screen shot 2015-02-19 at 16 43 42](https://cloud.githubusercontent.com/assets/299787/6271122/8fab0552-b856-11e4-9d00-532e151a7f4c.png)
After ![screen shot 2015-02-19 at 16 43 24](https://cloud.githubusercontent.com/assets/299787/6271125/99a9a89c-b856-11e4-859f-824e99890a9c.png)

**Comment by astrofrog** [comment]
Very nice implementation by @slowe in #25
