### ISSUE TITLE
Try and reduce boilerplate language

### ISSUE THREAD

**Issue by astrofrog** [astrofrog/acknowledgment-generator#15]
We don't want to necessarily have 'This research made use of...' repeated 20 times

**Comment by Cadair** [comment]
It needs some kind of template, either just detecting the text or having some specific place holder?

**Comment by astrofrog** [comment]
We could just also assume that all acknowledgments start with that, and not include it in the yaml files. Then we just do: `This research made use of [ack1]; [ack2]; [ack3]`. We could even use a slightly different start for the different sections `This paper includes observations from [ack4]; [ack5]; [ack6]` and so on. It might change some of the acknowledgments slightly. But basically I think the idea would be to get rid of the start of the sentence in all yaml files and add it in the javascript.

**Comment by slowe** [comment]
Yes, I'm having a similar problem in something I'm doing as I have lots of sources and I don't want the same bit of text repeated. Removing the start of the sentence in the yaml is probably a good idea. The Javascript could even allow for a user-specified separator. :)

**Comment by slowe** [comment]
I've had a go at concatenating anything containing "made use of". The results look like this...
Before 
![screen shot 2015-02-19 at 16 43 42](https://cloud.githubusercontent.com/assets/299787/6271166/d75580d0-b856-11e4-97f9-11425c9e045c.png)
After 
![screen shot 2015-02-19 at 16 43 24](https://cloud.githubusercontent.com/assets/299787/6271171/dc180764-b856-11e4-93c1-561ffe88bc25.png)

**Comment by slowe** [comment]
Isn't this issue a repeat of issue #1 ?

**Comment by astrofrog** [comment]
@slowe - it is indeed. Very nice work with avoiding the repeated text, I'll take a look at how you did it!

**Comment by astrofrog** [comment]
@slowe already took a stab at this, and will leave it open for now in case we want to make any further changes (but actually it looks nice at the moment)
