### ISSUE TITLE
First of all: refactor the crazy js code

### ISSUE THREAD

**Issue by onekiloparsec** [astrofrog/acknowledgment-generator#51]
Ongoing here: https://github.com/onekiloparsec/acknowledgment-generator

Will do a PR once I get an iso-features state.

@astrofrog Let me know if you want to participate.

**Comment by astrofrog** [comment]
Thanks!! I'm a total HTML + JS n00b :-/

**Comment by onekiloparsec** [comment]
I've made a lot of refactor. Not only in the javascript, but also in the python script that generate the JSON file. I've added basic Twitter bootstrap style. 

It is unclear to me the purpose of all the stuff you were doing with a delimiter in the old JS code. And what about the Facilities and Bibtex parts: how exactly they are built. Could you `clone` my fork and have a check?

I'll give you access to my fork for you to push right into it if necessary.

**Comment by astrofrog** [comment]
Done in #52 - thanks @onekiloparsec!
