### ISSUE TITLE
Migrate from Travis to GH actions 

### ISSUE THREAD

**Issue by hamogu** [astrofrog/acknowledgment-generator#82]
When reviewing #81, I noticed that the tests are not run any longer. I think that's because we are still set up for Travis. But that also means that there is no automatic deployment after merging. Thus, even if I confirm #81 locally, I can't get it on the live site.

Since the deployment requires a GH secrect, I'm not sure I can actually do that. @astrofrog : Can you have a look?

**Comment by astrofrog** [comment]
Done! In fact this doesn't require a custom secret, just the built-in ``GITHUB_TOKEN`` secret.
